import Link from "next/link";
import CaseStudyShell, { PanelCard } from "@/components/CaseStudyShell";
import { projectMetadata } from "@/lib/metadata";

export const metadata = projectMetadata("ML Reproducibility Auditor", "CLI-based evaluator for reproducibility, engineering quality, and ML systems patterns in GitHub repositories.", "/projects/repro-audit");

export default function ReproAuditPage() {
  return <CaseStudyShell identifier="PROJECT 08 · REPRODUCIBILITY" title="ML Reproducibility Auditor" updated="May 2026" introduction="Built a CLI-based system that uses GitHub API analysis to evaluate ML repositories for reproducibility, engineering quality, and systems-design patterns." links={<><a href="https://github.com/OmprakashSahani/ml-repro-audit" target="_blank" rel="noopener noreferrer">View Repository →</a><a href="https://asciinema.org/a/OgamYxdbBFK8FMZk" target="_blank" rel="noopener noreferrer">Watch Demo →</a></>} showBackLink={false} tabs={[
    { id: "overview", label: "Overview", content: <div><PanelCard title="Problem"><p>Many ML repositories lack reproducible environments, explicit seed control, and engineering discipline. Assessing their reliability otherwise requires manual inspection.</p></PanelCard><section className="atlas-technical-highlights" aria-labelledby="repro-technical-highlights-title"><h2 id="repro-technical-highlights-title" className="text-lg font-semibold">Technical Highlights</h2><p className="atlas-technology-list">Python · CLI · GitHub API · Static Analysis · ML Systems</p><ul><li>Reproducibility scoring system</li><li>GitHub API-based analysis</li><li>ML systems pattern detection</li></ul></section><Link href="/projects" className="case-study-back atlas-overview-back">← Back to Selected Projects</Link></div> },
    { id: "design", label: "System Design", content: <PanelCard title="System Design"><ul><li>Repository inspection through the GitHub API without cloning</li><li>Structure analysis for CI/CD, benchmarks, datasets, and packaging</li><li>Code-quality and determinism checks</li><li>Pattern detection for PyTorch, distributed training, and all-reduce</li><li>Scoring with reproducibility and risk classification</li></ul></PanelCard> },
    { id: "architecture", label: "Architecture", content: <section className="atlas-architecture-panel" aria-labelledby="repro-architecture-title"><h2 id="repro-architecture-title" className="text-xl font-semibold">Architecture</h2><p>The tool fetches repository metadata, analyzes structure and code signals, scores reproducibility, classifies risk, and generates actionable findings.</p><img src="/images/repro-audit-architecture.png" alt="ML Reproducibility Auditor analysis and scoring architecture" width="1536" height="1024" className="atlas-architecture-image" loading="lazy" /></section> },
    { id: "results", label: "Results", content: <div className="case-panel-grid atlas-natural-grid"><PanelCard title="Results and Insights"><ul><li>Identified missing reproducibility signals such as CI/CD and seed control.</li><li>Detected system patterns across real-world ML repositories.</li><li>Automated evaluation of engineering maturity.</li><li>Enabled comparison of infrastructure practices across projects.</li></ul></PanelCard><PanelCard title="Takeaway"><p>Reproducibility in ML systems depends on engineering practices, not only model design.</p></PanelCard></div> },
    { id: "verification", label: "Example Output", content: <PanelCard title="Example Output"><pre>{`Reproducibility Score: 7.5/10
Risk Level: MEDIUM
Missing CI/CD → Not automatically validated
Missing seed control → Not reproducible`}</pre></PanelCard> },
  ]} />;
}
