import Link from "next/link";
import CaseStudyShell, { PanelCard } from "@/components/CaseStudyShell";
import { projectMetadata } from "@/lib/metadata";

export const metadata = projectMetadata("Distributed Training Simulator", "Distributed training simulator for analyzing scaling efficiency, communication overhead, and system bottlenecks.", "/projects/distributed");

export default function DistributedPage() {
  return <CaseStudyShell identifier="PROJECT 05 · DISTRIBUTED SYSTEMS" title="Distributed Training Simulator" updated="May 2026" introduction="Built a distributed training simulator to analyze scaling efficiency, communication overhead, and the point where synchronization cost overtakes useful computation." links={<a href="https://github.com/OmprakashSahani/distml-core" target="_blank" rel="noopener noreferrer">View Repository →</a>} showBackLink={false} tabs={[
    { id: "overview", label: "Overview", content: <div><PanelCard title="Problem"><p>Adding workers does not guarantee faster training: model size, collective strategy, and network bandwidth determine when communication dominates each step.</p></PanelCard><section className="atlas-technical-highlights" aria-labelledby="distributed-technical-highlights-title"><h2 id="distributed-technical-highlights-title" className="text-lg font-semibold">Technical Highlights</h2><p className="atlas-technology-list">Python · Distributed Systems · All-Reduce · Performance Modeling</p><ul><li>~0.77 efficiency for small models</li><li>Compute-to-communication transition near eight workers</li><li>Negative scaling for 1000 MB models</li></ul></section><Link href="/projects" className="case-study-back atlas-overview-back">← Back to Selected Projects</Link></div> },
    { id: "design", label: "System Design", content: <PanelCard title="System Design"><ul><li>Data-parallel training with worker-level computation</li><li>Ring and tree all-reduce communication strategies</li><li>Step-time, speedup, and efficiency modeling</li><li>Communication ratio and bottleneck detection</li></ul></PanelCard> },
    { id: "architecture", label: "Architecture", content: <section className="atlas-architecture-panel" aria-labelledby="distributed-architecture-title"><h2 id="distributed-architecture-title" className="text-xl font-semibold">Architecture</h2><p>Compute and collective-communication models combine worker count, model size, and network bandwidth to estimate step time, speedup, efficiency, and bottleneck regime.</p><img src="/images/distml-architecture.png" alt="Distributed Training Simulator architecture" width="1536" height="1024" className="atlas-architecture-image" loading="lazy" /></section> },
    { id: "analysis", label: "Performance Analysis", content: <div className="case-panel-grid atlas-natural-grid"><PanelCard title="Results and Insights"><ul><li>Small models achieved near-linear scaling at ~0.77 efficiency.</li><li>Workloads became communication-bound near eight workers.</li><li>1000 MB models showed negative scaling from communication cost.</li><li>Bandwidth materially changed scalability at 1 GB/s versus 100 GB/s.</li><li>Ring all-reduce outperformed tree at higher worker counts.</li></ul></PanelCard><PanelCard title="Takeaway"><p>Distributed training stops scaling efficiently when communication overhead begins to dominate computation.</p></PanelCard></div> },
    { id: "benchmarks", label: "Benchmarks", content: <div className="case-panel-grid atlas-natural-grid"><PanelCard title="Communication Ratio"><img src="/images/gradient_size_comm_ratio.png" alt="Communication ratio across distributed training configurations" width="800" height="500" className="case-study-image" loading="lazy" /></PanelCard><PanelCard title="Scaling Behavior"><img src="/images/step_time_scaling.png" alt="Distributed training step-time scaling graph" width="800" height="500" className="case-study-image" loading="lazy" /></PanelCard></div> },
  ]} />;
}
