import Link from "next/link";
import CaseStudyShell, { PanelCard } from "@/components/CaseStudyShell";
import { projectMetadata } from "@/lib/metadata";

export const metadata = projectMetadata("Distributed Training Profiler", "Profiler for analyzing communication overhead, memory bottlenecks, and scaling efficiency in distributed ML workloads.", "/projects/profiler");

export default function ProfilerPage() {
  return <CaseStudyShell identifier="PROJECT 04 · PERFORMANCE ANALYSIS" title="Distributed Training Profiler" updated="May 2026" introduction="Built a systems profiler for analyzing communication overhead, memory bottlenecks, scaling efficiency, and optimization trade-offs in distributed ML workloads." links={<a href="https://github.com/OmprakashSahani/dist-training-profiler" target="_blank" rel="noopener noreferrer">View Repository →</a>} showBackLink={false} tabs={[
    { id: "overview", label: "Overview", content: <div><PanelCard title="Problem"><p>Distributed training can become communication- or memory-bound as worker count and model size grow. The profiler makes those constraints explicit before expensive runs.</p></PanelCard><section className="atlas-technical-highlights" aria-labelledby="profiler-technical-highlights-title"><h2 id="profiler-technical-highlights-title" className="text-lg font-semibold">Technical Highlights</h2><p className="atlas-technology-list">Python · Distributed Systems · All-Reduce · Performance Modeling · ZeRO</p><ul><li>Communication versus compute bottleneck analysis</li><li>ZeRO memory optimization simulation</li><li>Scaling-efficiency and overlap analysis</li></ul></section><Link href="/projects" className="case-study-back atlas-overview-back">← Back to Selected Projects</Link></div> },
    { id: "design", label: "System Design", content: <PanelCard title="System Design"><ul><li>Distributed training-step simulation</li><li>Ring all-reduce communication modeling</li><li>Communication-computation overlap analysis</li><li>GPU memory-feasibility estimation</li><li>ZeRO-1, ZeRO-2, and ZeRO-3 optimization modeling</li></ul></PanelCard> },
    { id: "architecture", label: "Architecture", content: <section className="atlas-architecture-panel" aria-labelledby="profiler-architecture-title"><h2 id="profiler-architecture-title" className="text-xl font-semibold">Architecture</h2><p>The simulator combines compute, communication, overlap, and optimizer-state models to expose step-time and memory bottlenecks across configurations.</p><img src="/images/profiler-architecture.png" alt="Distributed Training Profiler architecture" width="1536" height="1024" className="atlas-architecture-image" loading="lazy" /></section> },
    { id: "analysis", label: "Performance Analysis", content: <div className="case-panel-grid atlas-natural-grid"><PanelCard title="Results and Insights"><ul><li>Communication overhead increases with worker count.</li><li>Scaling efficiency degrades as synchronization dominates execution.</li><li>Compute overlap reduces effective synchronization cost.</li><li>Large models rapidly become memory-bound.</li><li>ZeRO optimization substantially reduces memory requirements.</li></ul><div className="mt-4"><h3 className="font-semibold text-gray-300">Takeaway</h3><p className="mt-2">Distributed performance depends on the interaction between compute, synchronization, memory capacity, and the optimization strategy.</p></div></PanelCard><img src="/images/scaling_efficiency.png" alt="Distributed Training Profiler scaling-efficiency analysis" width="800" height="500" className="case-study-image" loading="lazy" /></div> },
  ]} />;
}
