import type { Metadata } from "next";
import Link from "next/link";
import CaseStudyShell, { PanelCard } from "@/components/CaseStudyShell";

const description = "Search evaluation and regression-detection platform for benchmarking TF-IDF, BM25, and hybrid retrieval systems across relevance, latency, and query-level failure behaviour.";
export const metadata: Metadata = { title: "SearchEval Lab", description, alternates: { canonical: "/projects/searcheval-lab" }, openGraph: { title: "SearchEval Lab", description, url: "/projects/searcheval-lab", type: "article" }, twitter: { card: "summary", title: "SearchEval Lab", description } };
const jsonLd = { "@context": "https://schema.org", "@type": "SoftwareSourceCode", name: "SearchEval Lab", description, codeRepository: "https://github.com/OmprakashSahani/searcheval-lab", url: "https://ml-systems-portfolio.vercel.app/projects/searcheval-lab", author: { "@type": "Person", name: "Omprakash Sahani" }, programmingLanguage: "Python" };

export default function SearchEvalLabPage() {
  return <CaseStudyShell identifier="PROJECT 04 · SEARCH EVALUATION" title="SearchEval Lab" updated="July 2026" introduction="Built a search evaluation and regression-detection platform for benchmarking retrieval quality, latency, and query-level failure behaviour across TF-IDF, BM25, and hybrid search systems." structuredData={jsonLd} links={<a href="https://github.com/OmprakashSahani/searcheval-lab" target="_blank" rel="noopener noreferrer">GitHub Repository →</a>} showBackLink={false} tabs={[
    { id: "overview", label: "Overview", content: <div><PanelCard title="Problem"><p>Retrieval changes can improve aggregate relevance while hiding latency regressions or weak-query failures. SearchEval Lab evaluates those dimensions together against versioned evidence.</p></PanelCard><section className="atlas-technical-highlights" aria-labelledby="search-technical-highlights-title"><h2 id="search-technical-highlights-title" className="text-lg font-semibold">Technical Highlights</h2><p className="atlas-technology-list">Python · Information Retrieval · TF-IDF · BM25 · Hybrid Search · FastAPI · CI</p><ul><li>Relevance and latency evaluation</li><li>Versioned benchmark artifacts</li><li>Query-level failure analysis</li></ul></section><Link href="/projects" className="case-study-back atlas-overview-back">← Back to Selected Projects</Link></div> },
    { id: "design", label: "System Design", content: <PanelCard title="System Design"><ul><li>Validated documents, queries, and relevance judgments</li><li>TF-IDF, BM25, and hybrid retrieval through a search-engine factory</li><li>Precision@k, Recall@k, MRR@k, and NDCG@k evaluation</li><li>Average, minimum, and maximum latency measurement</li><li>Versioned artifacts with configurable regression thresholds</li><li>Weak-query analysis, Markdown reporting, CLI, FastAPI, tests, and CI</li></ul></PanelCard> },
    { id: "architecture", label: "Architecture", content: <PanelCard title="Architecture"><p>Validated datasets feed a configurable search-engine factory. Evaluators compute relevance and latency metrics, compare versioned artifacts against thresholds, and produce query-level failure analysis and Markdown reports through CLI and FastAPI workflows.</p></PanelCard> },
    { id: "results", label: "Results", content: <div className="case-panel-grid atlas-natural-grid"><PanelCard title="Documented BM25 Results"><dl className="case-metrics"><div className="case-metric"><dt>Precision@10</dt><dd>0.1900</dd></div><div className="case-metric"><dt>Recall@10</dt><dd>1.0000</dd></div><div className="case-metric"><dt>MRR@10</dt><dd>0.9500</dd></div><div className="case-metric"><dt>NDCG@10</dt><dd>0.9198</dd></div></dl></PanelCard><PanelCard title="Takeaway"><p>Search evaluation is most useful when relevance, latency, versioned evidence, and query-level failures are assessed together.</p></PanelCard></div> },
  ]} />;
}
