import Link from "next/link";
import CaseStudyShell, { PanelCard } from "@/components/CaseStudyShell";
import { projectMetadata } from "@/lib/metadata";

export const metadata = projectMetadata("Autograd Engine", "Reverse-mode automatic differentiation engine with dynamic computation graphs and topological backpropagation.", "/projects/autograd");

export default function AutogradPage() {
  return <CaseStudyShell identifier="PROJECT 07 · AUTOMATIC DIFFERENTIATION" title="Autograd Engine" updated="May 2026" introduction="Built a reverse-mode autodiff engine from scratch to understand computation-graph construction and execution, with emphasis on correctness, scalability, and gradient-system trade-offs." links={<a href="https://github.com/OmprakashSahani/autograd-engine" target="_blank" rel="noopener noreferrer">View Repository →</a>} showBackLink={false} tabs={[
    { id: "overview", label: "Overview", content: <div><PanelCard title="Problem"><p>ML frameworks hide gradient computation and graph execution. Rebuilding autograd from first principles makes their correctness and systems trade-offs observable.</p></PanelCard><section className="atlas-technical-highlights" aria-labelledby="autograd-technical-highlights-title"><h2 id="autograd-technical-highlights-title" className="text-lg font-semibold">Technical Highlights</h2><p className="atlas-technology-list">Python · NumPy · Autograd · Backpropagation · Performance Analysis</p><ul><li>~1e-10 gradient error</li><li>Scales to 10,000+ nodes</li><li>Iterative DFS avoids recursion limits</li></ul></section><Link href="/projects" className="case-study-back atlas-overview-back">← Back to Selected Projects</Link></div> },
    { id: "design", label: "System Design", content: <PanelCard title="System Design"><ul><li>Dynamic define-by-run computation graph</li><li>Reverse-mode autodiff with topological traversal</li><li>Gradient accumulation across dependency paths</li><li>Iterative traversal for deep graphs</li></ul></PanelCard> },
    { id: "architecture", label: "Architecture", content: <section className="atlas-architecture-panel" aria-labelledby="autograd-architecture-title"><h2 id="autograd-architecture-title" className="text-xl font-semibold">Architecture</h2><p>Forward execution builds a dynamic graph; reverse-mode differentiation then traverses its topological order and accumulates gradients through every dependency path.</p><img src="/images/autograd-architecture.png" alt="Autograd engine computation graph and backward-pass architecture" width="1536" height="1024" className="atlas-architecture-image" loading="lazy" /></section> },
    { id: "results", label: "Results", content: <div className="case-panel-grid atlas-natural-grid"><PanelCard title="Results and Insights"><ul><li>Gradient correctness validated at approximately 1e-10 error.</li><li>Backward execution scaled approximately linearly with graph size.</li><li>Recursive traversal reached depth limits near 1,000 nodes.</li><li>Iterative DFS extended execution beyond 10,000 nodes.</li><li>Flexibility trades against memory use and execution overhead.</li></ul></PanelCard><PanelCard title="Takeaway"><p>Autograd performance depends on graph traversal, memory behavior, and execution overhead as well as mathematical correctness.</p></PanelCard></div> },
    { id: "benchmark", label: "Benchmark", content: <div className="case-panel-grid atlas-natural-grid"><PanelCard title="Backward-Pass Benchmark"><p>Backward-pass time increases with graph size, demonstrating near-linear scaling behavior.</p></PanelCard><img src="/images/backward_benchmark.png" alt="Autograd backward-pass benchmark by graph size" width="800" height="500" className="case-study-image" loading="lazy" /></div> },
  ]} />;
}
